#!/usr/bin/env python
# -*- coding: utf-8 -*-

def configure (conf):
	conf.check_tool('gcc')

def build (bld):
	bld.new_task_gen(
		features = 'cc cshlib',
		source = ['mrut.c'],
		includes = ['.', '../include'],
		target = 'hdMrut',
		install_path = '${PREFIX}/lib',
                uselib = ['HDTRACING', 'GLIB-2.0'],
	)

	bld.new_task_gen(
		features = 'cc cstaticlib',
		source = ['mrut.c'],
		includes = ['.', '../include'],
		target = 'hdMrut',
		install_path = '${PREFIX}/lib',
                uselib = ['HDTRACING', 'GLIB-2.0'],
	)