#!/usr/bin/env python
# -*- coding: utf-8 -*-

def configure (conf):
	conf.check_tool('gcc')

def build (bld):
	bld.new_task_gen(
		features = 'cc cshlib',
		source = ['common.c','hash_tables.c','hdMPITracer.c','hdTraceMPIWrapper.c','mpi_names.c','write_info.c'],
		includes = ['.', '../include'],
		target = 'HDMPIWrapper',
		install_path = '${PREFIX}/lib',
                uselib = ['HDTRACING', 'RUT', 'PTHREAD','GLIB-2.0'],
	)
	
	bld.new_task_gen(
		features = 'cc cstaticlib',
		source = ['common.c','hash_tables.c','hdMPITracer.c','hdTraceMPIWrapper.c','mpi_names.c','write_info.c'],
		includes = ['.', '../include'],
		target = 'HDMPIWrapper',
		install_path = '${PREFIX}/lib',
                uselib = ['HDTRACING', 'RUT', 'PTHREAD','GLIB-2.0'],
	)
