#!/usr/bin/env python

import Options
import os
import Utils

def build (bld):

	bld.new_task_gen(
		features = 'cc cprogram',
		source = ['traceAll.c'],
		includes = ['../include'],
		uselib = ['GLIB-2.0', 'G-THREAD-2.0', 'LIBGTOP-2.0', 'HDTRACE', 'HDSTATS', 'DBCONNECTOR'],
		uselib_local = ['RUT'],
		target = 'traceAll',
		install_path = '${PREFIX}/examples'
	)

	bld.new_task_gen(
		features = 'cc cprogram',
		source = ['traceLoop.c'],
		includes = ['../include'],
		uselib = ['GLIB-2.0', 'G-THREAD-2.0', 'LIBGTOP-2.0', 'HDTRACE', 'HDSTATS', 'DBCONNECTOR'],
		uselib_local = ['RUT'],
		target = 'traceLoop',
		install_path = '${PREFIX}/examples'
	)

	bld.new_task_gen(
		features = 'cc cprogram',
		source = ['traceLoop2.c'],
		includes = ['../include'],
		uselib = ['GLIB-2.0', 'G-THREAD-2.0', 'LIBGTOP-2.0', 'HDTRACE', 'HDSTATS', 'DBCONNECTOR'],
		uselib_local = ['RUT'],
		target = 'traceLoop2',
		install_path = '${PREFIX}/examples'
	)
