#ifndef _CONSTANT_H_
#define _CONSTANT_H_

#define HOST_NAME_LEN 255
#define PATH_LEN 4096
#define PROGRAMM_NAME_LEN 255
#define COMM_NAME_LEN 255
#define CHUNK_LEN 20
#define DATA_TYPE_NAME_LEN 255
#define MPI_ERROR_LEN 255
#endif
