/**
* \author Johann Weging
* \date 2010-11-23
*/

#ifndef _READTRACE_H_
#define _READTRACE_H_

#include <glib.h>
#include <expat.h>

#include "readxml.h"

struct UserDataTrace
{
	int depth;
	GSList* elements;
	int isNested;

};
/**
* This function reads the *.trc files, generated by HDTrace.
*/
void read_trace(GSList**, gchar*);


void XMLCALL start_trace_element(struct UserDataTrace *userData, 
		const char *name, const char** attributes);

void XMLCALL end_trace_element(struct UserDataTrace *userData,
		const char* name);

#endif
