/**
* \author Johann Weging
* \date 2010-11-23
*/

#ifndef _READTRACE_H_
#define _READTRACE_H_

#include <string.h>
#include <glib.h>
#include <stdio.h>
#include "structures.h"
#include "error.h"
#include "readxml.h"

/**
* This function reads the *.trc files, generated by HDTrace.
*/
void read_trace(GSList**, char*);

#endif
