#ifndef _READPROJECT_H_
#define _READPROJECT_H_

#include "readxml.h"
#include "structures.h"
#include "error.h"
#include <stdio.h>
#include <string.h>
#include "constant.h"
#include "readxml.h"

/**
  \brief Reads the project file generated by HDTrace.
  
  \param[in] filename The Path to the project file.
  \param[out] hostname The hostname of the node the rank was executed on.
  \param[out] com A list of the communicators used of the traced program.
  \param[out] programName The name of the traced program.
  
  The function reads multiple information of the project file needed for 
  the generation of the trace file names and communicators used in the traces 
  program. 
*/
void
readproject(char* programName, char* hostname, GSList** com, int rank,  char* filename);
#endif
