#!/usr/bin/env python

def configure (conf):
	conf.check_tool('gcc')

def build (bld):
	bld.new_task_gen(
		features = 'cc cprogram',
		source = ['ptLoop.c'],
		includes = ['../include', '../src'],
		uselib = ['HDTRACING'],
		uselib_local = ['pt'],
		target = 'ptLoop',
		install_path = None
	)

	'''
run_ptLoop: ptLoop
	./ptLoop ../pt.cfg
	'''
