#!/usr/bin/env python

import Utils
import Options
import os

def build (bld):

	bld.new_task_gen(
		features = 'cc cshlib',
		source = ['RUT.c','tracing.c'],
		includes = ['.', '../include'],
		uselib = ['GLIB-2.0','GTHREAD-2.0','LIBGTOP-2.0','DBCONNECTOR','PG','HDTRACE'],
		target = 'RUT',
		install_path = '${PREFIX}/lib',
		linkflags = ['-fPIG']
	)

