#!/bin/sh

JVM=/usr/bin/java
JVMFLAGS="-Xmx950m -Xss100m"

# Set PATH to the jar needed by the print program
GUI_LIBDIR=$(dirname $0)/lib
GUI_HOME=${GUI_LIBDIR}/
MAIN_LIB=${GUI_LIBDIR}/ProcessToGradient.jar


if [ -z "${GUI_LIBDIR}" -o "${GUI_LIBDIR}" = "/lib" ]; then
    echo "GUI_LIBDIR is NOT set!"
    exit 1
else
    echo "GUI_LIBDIR is set. GUI_LIBDIR = "${GUI_LIBDIR}
fi

${JVM} ${JVMFLAGS} -jar ${MAIN_LIB} "$@"
