#!/usr/bin/env python
# -*- coding: utf-8 -*-

def configure (conf):
	conf.check_tool('gcc')

def build (bld):
	bld.new_task_gen(
		features = 'cc cstaticlib cshlib',
		source = ['hdTrace.c', 'hdTopo.c', 'common.c', 'util.c'],
		includes = ['.', '../include'],
		target = 'hdTrace',
		install_path = '${PREFIX}/lib'
	)

	bld.new_task_gen(
		features = 'cc cstaticlib cshlib',
		source = ['hdStats.c', 'hdTopo.c', 'common.c', 'util.c'],
		includes = ['.', '../include'],
		target = 'hdStats',
		install_path = '${PREFIX}/lib'
	)

	bld.new_task_gen(
		features = 'cc cstaticlib cshlib',
		source = ['hdRelation.c', 'hdTopo.c', 'common.c', 'util.c'],
		includes = ['.', '../include'],
		target = 'hdRelation',
		install_path = '${PREFIX}/lib'
	)

	bld.new_task_gen(
		features = 'cc cstaticlib cshlib',
		source = ['hdTrace.c', 'hdTopo.c', 'hdStats.c', 'hdRelation.c', 'common.c', 'util.c'],
		includes = ['.', '../include'],
		target = 'hdTracing',
		install_path = '${PREFIX}/lib'
	)

